<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
  
    <title>Grecia antica</title>
   <?php include("includes/header.html");?>
  </head>

<body>

<?php include("includes/navigation.html");?>

<div class="main home">
	<div class="container">
	<br>
	<h3 class="subtitle">Localizare</h3>
	<p><strong>O țară muntoasă, cu țărmuri crestate, înconjurate de insule.</strong> În sud-estul Europei, în partea cea mai de sud a Peninsulei Balcanice, înaintând în Marea Mediterană, ca o mână cu degetele răsfirate, se află Grecia. În antichitate era numită Elada. Ea mai cuprindea și insulele din jurul ei, precum și țărmul Asiei Mici. Țara este scăldată în apele mării (la Est de Marea Egee, la sud, de Marea Mediterană, în vest, de Marea Ionică). În nord, se mărginea cu Macedonia și Tracia.</p>
		<div class="row">
			<div class="col-md-6">  
			<br>
				<h3 class="subtitle">Triburile grecesti</h3>
				<ul>
					<li><p><span style="font-weight: bold">aheii</span> - în Pelopones au creat civilizația miceniană - la începutul mileniului II î.Hr</p></li>
					<li><p><span style="font-weight: bold">ionienii</span> - în Grecia centrală</p></li>
					<li><p><span style="font-weight: bold">eolienii</span> - în Thesalia și Beoția</p></li>
					<li><p><span style="font-weight: bold">dorienii</span> - au distrus civilizația miceniană; sub presiunea dorienilor, grupuri de eolieni și ionieni s-au stabilit pe litoralul apusean al Asiei mici</p></li>
				</ul>
				<h3 class="subtitle">Periodizare</h3>
				<ul>
					<li><p><span style="font-weight: bold">Civilizația cretană</span> - sec XXIII-XV î.Hr <i style="color:#b5502e; font-size:1.2em;"  class="fa fa-question-circle" aria-hidden="true" bubble-text='Expresia “Ia taurul de coarne”, vine din mitologia greac,(Legenda lui Hercule care a salvat i-la Creta de un taur fioros, luându-l de coarne)'></i></p></li>
					<li><p><span style="font-weight: bold">Civilizația miceniană</span> - sec XV-XII î.Hr</p></li>
					<li><p><span style="font-weight: bold">Veacurile întunecate</span> - sec XII-VIII î.Hr</p></li>
					
					<li><a role="button" data-toggle="collapse" href="#collapse3" aria-expanded="false" aria-controls="collapse3"><p><span style="font-weight: bold">Marea colonizare</span> - sec VIII-VI î.Hr</p></a></li>
					<div class="collapse" id="collapse3">
						<div style="overflow-y:scroll; max-height:220px;" class="card">
							<div class="card-block">
								<h4>Cauze</h4>
								<p>În cetățile Greciei antice, toate drepturile unui om depindeau de stăpânirea asupra pământului. Din această pricină, atunci când - datortă sărăcirii unora - o parte din cetățeni nu au mai avut pământ destul, cetățile  au hotărât să trimită departe, peste mare, un grup de cetățeni  care să întemeieze acolo un nou oraș - o colonie. </p>
								<h4>Principalele colonii</h4>
								<p>Orașele din care proveneau coloniile se numeau metropole(orașe-mamă), iar cele nou-întemeiate apoikii(noi le numim colonii).  </p>
								<ul>
									<li>Cele mai importante metropole au fost: Milet, Corint, Megara</li>
									<li>Principalele colonii grecești au fost:</li>
									Tarent, Neapolis, Siracuza - în pen. Italică, Massalia - în sudul Franței, Histria, Tomis (Constanța), Callatis (Mangalia) pe țărmul Mării Negre, Naucratis și Cirene în nordul Africii. </li>
								</ul>
          		
							</div>
						</div>
					</div>
					<li><p><a target="_blank" href="http://www.rasfoiesc.com/educatie/istorie/EPOCA-CLASICA-A-GRECIEI-ANTICE98.php"><span style="font-weight: bold">Perioada clasică</span> - sec VI-IV î.Hr</a></p></li>
					<li><p><a target="_blank" href="http://www.ipedia.ro/epoca-elenistica-enciclopedie-informatii-istorie-708/"><span style="font-weight: bold">Epoca elenistică </span> - sec IV-31 î.Hr. </a></p></li>
				</ul>
			</div><!-- col-md-6 -->
			<div class="col-md-6 r-img-container">
				<br>
				<img id="map" src="images/map.jpg">
			</div><!-- col-md-6 -->
		</div><!-- row -->
		
	<div id="splash"><!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/raft.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="" title="" id="splash-map" coords="238,815,446,120" shape="rect">
</map>
	</div>
	</div><!-- container -->

	
	
	<script>$(document).ready(function() {
    $('#splash-map').click(function() {
       $('#splash').fadeOut(1500);
    });
	
	});</script>

	<style>#splash {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
	opacity:1;
	overflow:hidden;}</style>
	
	<!--<script>
$( '#splash-map' ).click(function() {
    $( "#splash-map" ).slideUp();
  }
});
</script>-->
	
	
	</div><!-- home -->


<?php include("includes/footer.html");?>

	
</body>
</html>